using Mutagen.Bethesda;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Noggog;
using StringCompareSettings;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace SynAutomaticSpells
{
    public class Program
    {
        static Lazy<PatcherSettings> Settings = null!;
        public static async Task<int> Main(string[] args)
        {
            return await SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings("PatcherSettings", "settings.json", out Settings)
                .SetTypicalOpen(GameRelease.SkyrimSE, "SynAutomaticSpells.esp")
                .Run(args);
        }

        public class NPCInfo
        {
            public readonly Dictionary<FormKey, List<IKeywordGetter>> HandEffects = new();
            public readonly Dictionary<Skill, uint> SkillLevels = new();

            internal void AddEquipTypeKeywords(IFormLinkNullableGetter<IEquipTypeGetter> equipSlot, IKeywordGetter keyword)
            {
                if (!HandEffects.ContainsKey(equipSlot.FormKey))
                {
                    HandEffects.Add(equipSlot.FormKey, new() { keyword });
                }
                else
                {
                    HandEffects[equipSlot.FormKey].Add(keyword);
                }
            }
        }

        public class SpellInfo
        {
            public ISpellGetter? Spell;
            public Skill? MainSkill;
            public IMagicEffectGetter? MainEffect;
            public Dictionary<Skill, uint> RequiredSkills = new();
        }

        static bool DebugSpell = false;
        static IPatcherState<ISkyrimMod, ISkyrimModGetter>? State;
        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
        {
            State = state;

            SearchAndTryReadASISIni();

            SetAsisAutoSpellsIniValuesToSettings();

            // get spell infos
            Console.WriteLine("Get spells info..");
            var spellInfoList = GetSpellInfoList();
            Console.WriteLine("Get npc info..");
            var npcsInfoList = GetNPCInfoList();

            Console.WriteLine("Distribute spells to npcs..\n-----------");
            int patchedNpcCount = 0;
            foreach (var npcInfo in npcsInfoList)
            {
                bool isnpcdebug = false;
                if (npcInfo.Key.EditorID== "Madena")
                {
                    Console.WriteLine("Madena!");
                    isnpcdebug = true;
                }

                if(isnpcdebug) Console.WriteLine("Madena! 1");
                var spellsToAdd = new List<ISpellGetter>();
                foreach (var spellInfo in spellInfoList)
                {
                    DebugSpell = false;
                    if(isnpcdebug && spellInfo.Key.EditorID== "ZZFireChannel")
                    {
                        Console.WriteLine("ZZFireChannel!");
                        DebugSpell = true;
                    }
                    if(DebugSpell) Console.WriteLine("ZZFireChannel 1");
                    if (!CanGetTheSpell(npcInfo.Value, spellInfo)) continue;
                    if (DebugSpell) Console.WriteLine("ZZFireChannel 2");
                    if (npcInfo.Key.ActorEffect!.Contains(spellInfo.Key)) continue;
                    if (DebugSpell) Console.WriteLine("ZZFireChannel 3");

                    spellsToAdd.Add(spellInfo.Key);
                }

                if (isnpcdebug) Console.WriteLine("Madena! 2");
                var addedCount = spellsToAdd.Count;
                if (addedCount == 0) continue;

                if (isnpcdebug) Console.WriteLine("Madena! 3");
                //Console.WriteLine($"Add {addedCount} spells for '{npcInfo.Key.EditorID}'");
                var npc = state.PatchMod.Npcs.GetOrAddAsOverride(npcInfo.Key);
                foreach (var spellToAdd in spellsToAdd) npc.ActorEffect!.Add(spellToAdd);
                patchedNpcCount++;
            }

            Console.WriteLine($"\n\nPatched {patchedNpcCount} npcs.\n-----------");
        }

        private static void SetAsisAutoSpellsIniValuesToSettings()
        {
            Console.WriteLine("Set Asis autospells ini values into settings..");

            foreach (var v in AutomaticSpellsIniParams!["NPCInclusions"])
            {
                var stringInfo = new StringCompareSetting
                {
                    Name = v,
                    IgnoreCase = true,
                    Compare = CompareType.StartsWith
                };

                var list = Settings.Value.NpcInclude;
                if (list.Contains(stringInfo)) continue;

                list.Add(stringInfo);
            }
            foreach (var v in AutomaticSpellsIniParams["NPCExclusions"])
            {
                var stringInfo = new StringCompareSetting
                {
                    Name = v,
                    IgnoreCase = true,
                    Compare = CompareType.Contains
                };

                var list = Settings.Value.NpcExclude;
                if (list.Contains(stringInfo)) continue;

                list.Add(stringInfo);
            }
            foreach (var v in AutomaticSpellsIniParams["SPELLEXCLUSIONSCONTAINS"])
            {
                var stringInfo = new StringCompareSetting
                {
                    Name = v,
                    IgnoreCase = true,
                    Compare = CompareType.Contains
                };

                var list = Settings.Value.SpellExclude;
                if (list.Contains(stringInfo)) continue;

                list.Add(stringInfo);
            }
            foreach (var v in AutomaticSpellsIniParams["SPELLEXCLUSIONSSTARTSWITH"])
            {
                var stringInfo = new StringCompareSetting
                {
                    Name = v,
                    IgnoreCase = true,
                    Compare = CompareType.StartsWith
                };

                var list = Settings.Value.SpellExclude;
                if (list.Contains(stringInfo)) continue;

                list.Add(stringInfo);
            }
            foreach (var v in AutomaticSpellsIniParams["EffectKeywordPrefixes"])
            {
                var stringInfo = new StringCompareSetting
                {
                    Name = v,
                    IgnoreCase = true,
                    Compare = CompareType.StartsWith
                };

                var list = Settings.Value.EffectKeywordInclude;
                if (list.Contains(stringInfo)) continue;

                list.Add(stringInfo);
            }
            foreach (var v in AutomaticSpellsIniParams["NPCKeywordExclusions"])
            {
                var stringInfo = new StringCompareSetting
                {
                    Name = v,
                    IgnoreCase = true,
                    Compare = CompareType.StartsWith
                };

                var list = Settings.Value.NpcKeywordExclude;
                if (list.Contains(stringInfo)) continue;

                list.Add(stringInfo);
            }
            foreach (var v in AutomaticSpellsIniParams["NPCModExclusions"])
            {
                var stringInfo = new StringCompareSetting
                {
                    Name = v,
                    IgnoreCase = true,
                    Compare = CompareType.Equals
                };

                var list = Settings.Value.NpcModNameExclude;
                if (list.Contains(stringInfo)) continue;

                list.Add(stringInfo);
            }
            foreach (var v in AutomaticSpellsIniParams["spellModInclusions"])
            {
                var stringInfo = new StringCompareSetting
                {
                    Name = v,
                    IgnoreCase = true,
                    Compare = CompareType.Equals
                };

                var list = Settings.Value.SpellModNameInclude;
                if (list.Contains(stringInfo)) continue;

                list.Add(stringInfo);
            }

            AutomaticSpellsIniParams = null;
        }

        public static Dictionary<string, HashSet<string>>? AutomaticSpellsIniParams = new()
        {
            { "NPCInclusions", new HashSet<string>() },
            { "NPCExclusions", new HashSet<string>() },
            { "SPELLEXCLUSIONSCONTAINS", new HashSet<string>() },
            { "SPELLEXCLUSIONSSTARTSWITH", new HashSet<string>() },
            { "EffectKeywordPrefixes", new HashSet<string>() },
            { "NPCKeywordExclusions", new HashSet<string>() },
            { "NPCModExclusions", new HashSet<string>() },
            { "spellModInclusions", new HashSet<string>() },
        };

        private static void SearchAndTryReadASISIni()
        {
            var iniPath = Path.Combine(State!.DataFolderPath, "SkyProc Patchers", "ASIS", "AutomaticSpells.ini");
            if (!File.Exists(iniPath)) return;

            // read AutomaticSpells ini parameters into settings
            Console.WriteLine("Found ASIS 'AutomaticSpells.ini'. Trying to read..");

            Dictionary<string, HashSet<string>> iniSections = new();
            iniSections.ReadIniSectionValuesFrom(iniPath);

            var keys = new HashSet<string>(AutomaticSpellsIniParams!.Keys);
            int iniValuesCount = 0;
            int iniSectionsCount = 0;
            foreach (var key in keys)
            {
                if (!iniSections.ContainsKey(key)) continue;

                var v = iniSections[key];
                AutomaticSpellsIniParams[key] = v;
                iniValuesCount += v.Count;
                iniSectionsCount++;
            }

            Console.WriteLine($"Added {iniSectionsCount} sections and {iniValuesCount} values from 'AutomaticSpells.ini'");
        }
        
        static bool isnpcdebug = false;
        private static Dictionary<INpcGetter, NPCInfo> GetNPCInfoList()
        {
            bool useNpcModExclude = Settings.Value.NpcModExclude.Count > 0;
            bool useNpcModExcludeByName = Settings.Value.NpcModExclude.Count > 0;
            bool useNpcExclude = Settings.Value.NpcExclude.Count > 0;
            bool useNpcInclude = Settings.Value.NpcInclude.Count > 0;
            bool useNpcKeywordExclude = Settings.Value.NpcKeywordExclude.Count > 0;
            var npcInfoList = new Dictionary<INpcGetter, NPCInfo>();
            foreach (var npcGetterContext in State!.LoadOrder.PriorityOrder.Npc().WinningContextOverrides())
            {
                if (npcGetterContext == null) continue;
                isnpcdebug = false;
                if (npcGetterContext.Record.EditorID == "Madena")
                {
                    Console.WriteLine("Madena!");
                    isnpcdebug = true;
                }

                if (isnpcdebug) Console.WriteLine("Madena! 21");
                // skip invalid
                var npcGetter = npcGetterContext.Record;
                if (npcGetter == null) continue;
                if (isnpcdebug) Console.WriteLine("Madena! 22");
                var sourceModKey = State!.LinkCache.ResolveAllContexts<INpc, INpcGetter>(npcGetter.FormKey).Last().ModKey;

                if (isnpcdebug) Console.WriteLine("Madena! 23");
                if (useNpcModExclude && Settings.Value.NpcModExclude.Contains(sourceModKey)) continue;
                if (isnpcdebug) Console.WriteLine("Madena! 24");
                if (useNpcModExcludeByName && sourceModKey.FileName.String.HasAnyFromList(Settings.Value.NpcModNameExclude)) continue;

                if (isnpcdebug) Console.WriteLine("Madena! 25");
                if (npcGetter.ActorEffect == null) continue;
                if (isnpcdebug) Console.WriteLine("Madena! 26");
                if (string.IsNullOrWhiteSpace(npcGetter.EditorID)) continue;
                if (isnpcdebug) Console.WriteLine("Madena! 27");
                if (useNpcExclude && npcGetter.EditorID.HasAnyFromList(Settings.Value.NpcExclude)) continue;
                if (isnpcdebug) Console.WriteLine("Madena! 28");
                if (useNpcInclude && !npcGetter.EditorID.HasAnyFromList(Settings.Value.NpcInclude)) continue;
                if (isnpcdebug) Console.WriteLine("Madena! 29");
                if (useNpcKeywordExclude && npcGetter.Keywords != null)
                {
                    bool skip = false;
                    foreach (var keywordGetterFormLink in npcGetter.Keywords)
                    {
                        if (!keywordGetterFormLink.TryResolve(State!.LinkCache, out var keywordGeter)) continue;
                        if (string.IsNullOrWhiteSpace(keywordGeter.EditorID)) continue;

                        if (!keywordGeter.EditorID.HasAnyFromList(Settings.Value.NpcKeywordExclude)) continue;

                        skip = true;
                        break;
                    }

                    if (isnpcdebug) Console.WriteLine("Madena! 30");
                    if (skip) continue;
                }

                if (isnpcdebug) Console.WriteLine("Madena! 31");
                NPCInfo? npcInfo = GetNPCInfo(npcGetter);
                if (npcInfo == null) continue;
                if (isnpcdebug) Console.WriteLine("Madena! 32");

                npcInfoList.Add(npcGetter, npcInfo);
            }

            return npcInfoList;
        }

        private static NPCInfo? GetNPCInfo(INpcGetter npcGetter)
        {
            if (isnpcdebug) Console.WriteLine("GetNPCInfo 1");
            INpcGetter? unTemplatedNpcSpells = UnTemplate(npcGetter, NpcConfiguration.TemplateFlag.SpellList);
            if (unTemplatedNpcSpells == null) return null;

            if (isnpcdebug) Console.WriteLine("GetNPCInfo 2");
            INpcGetter? unTemplatedNpcStats = UnTemplate(npcGetter, NpcConfiguration.TemplateFlag.Stats);
            if (unTemplatedNpcStats == null) return null;

            if (isnpcdebug) Console.WriteLine("GetNPCInfo 3");
            var npcInfo = new NPCInfo();
            // FireDamageConcAimed
            // get effects per equipSlot
            var spells = unTemplatedNpcSpells.ActorEffect;
            var npcSpellEffectsInfo = new Dictionary<ISpellGetter, IMagicEffectGetter>();
            foreach (var spellRecordGetterFormLink in spells!)
            {
                // reconvert from ispellrecordgetter to ispellrecord
                //if (!spellRecordGetterFormLink.TryResolve(State!.LinkCache, out var spellRecordGetter)) continue;
                var spellGetterFormlink = new FormLink<ISpellGetter>(spellRecordGetterFormLink.FormKey);
                if (spellGetterFormlink == null) continue;
                if (!spellGetterFormlink.TryResolve(State!.LinkCache, out var spellGetter)) continue;

                uint curCost = default;
                bool firstMainIsSet = false; // control to set first main effect because curcost is 0
                IMagicEffectGetter? mainEffect = null;
                foreach (var mEffect in spellGetter.Effects)
                {
                    if (mEffect == null
                        || mEffect.Data == null
                        || mEffect.BaseEffect.IsNull
                        || mEffect.BaseEffect.FormKey.IsNull) continue;

                    if (!mEffect.BaseEffect.TryResolve(State!.LinkCache, out var effect)) continue;
                    DebugSpell = false;
                    if (isnpcdebug && effect.EditorID== "FireDamageConcAimed")
                    {
                        Console.WriteLine($"{effect.EditorID}");
                        DebugSpell = true;
                    }
                    if (DebugSpell) Console.WriteLine($"{effect.EditorID} 1");

                    float mag = mEffect.Data!.Magnitude;
                    if (mag < 1) mag = 1;

                    int dur = mEffect.Data.Duration;
                    if (dur == 0) dur = 10;

                    if (DebugSpell) Console.WriteLine($"{effect.EditorID} 2");
                    var cost = CalcCost(effect.BaseCost, mag, dur);
                    if (DebugSpell) Console.WriteLine($"{effect.EditorID} : ,{nameof(effect.BaseCost)}:{spellGetter.BaseCost},{nameof(mag)}:{mag},{nameof(dur)}:{dur},{nameof(cost)}:{cost},{nameof(curCost)}:{curCost},{nameof(firstMainIsSet)}:{firstMainIsSet}");
                    if (!firstMainIsSet || cost > curCost)
                    {
                        if (DebugSpell) Console.WriteLine($"{effect.EditorID} 3");
                        firstMainIsSet = true;
                        curCost = cost;
                        mainEffect = effect;
                    }
                }

                if (isnpcdebug) Console.WriteLine("GetNPCInfo 4");
                if (mainEffect == null) continue;

                if (isnpcdebug) Console.WriteLine("GetNPCInfo 5");
                npcSpellEffectsInfo.Add(spellGetter, mainEffect);
            }

            if (isnpcdebug) Console.WriteLine("GetNPCInfo 4");
            if (npcSpellEffectsInfo.Count == 0) return null;

            if (isnpcdebug) Console.WriteLine("GetNPCInfo 5");
            foreach (var entry in npcSpellEffectsInfo)
            {
                if (entry.Value == null) continue;
                if (entry.Value.Keywords == null) continue;

                var equipType = entry.Key.EquipmentType;
                foreach (var keywordGetterFormLink in entry.Value!.Keywords!)
                {
                    if (!keywordGetterFormLink.TryResolve(State!.LinkCache, out var keywordGeter)) continue;
                    if (string.IsNullOrWhiteSpace(keywordGeter.EditorID)) continue;

                    if (keywordGeter.EditorID.HasAnyFromList(Settings.Value.EffectKeywordInclude)) npcInfo.AddEquipTypeKeywords(equipType, keywordGeter);
                }
            }

            // add skill level values of the npc
            List<Skill> skills = new()
            {
                Skill.Alteration,
                Skill.Conjuration,
                Skill.Destruction,
                Skill.Illusion,
                Skill.Restoration
            };
            foreach (Skill skill in skills)
            {
                npcInfo.SkillLevels.Add(skill, (uint)(unTemplatedNpcStats.PlayerSkills!.SkillValues[skill] + unTemplatedNpcStats.PlayerSkills.SkillOffsets[skill]));
            }

            if (isnpcdebug) Console.WriteLine("GetNPCInfo 6");
            return npcInfo;
        }

        private static INpcGetter? UnTemplate(INpcGetter npcGetter, NpcConfiguration.TemplateFlag templateFlag)
        {
            INpcGetter? untemplatedNpc = npcGetter;
            while (untemplatedNpc.Configuration.TemplateFlags.HasFlag(templateFlag))
            {
                if (untemplatedNpc.Template == null
                    || untemplatedNpc.Template.IsNull
                    || untemplatedNpc.Template.FormKey.IsNull
                    || !untemplatedNpc!.Template.TryResolve(State!.LinkCache, out var templateNpcSpawnGetter)
                    )
                {
                    untemplatedNpc = null;
                    break;
                }

                var templateNpcGetterFormlink = new FormLink<INpcGetter>(templateNpcSpawnGetter.FormKey);
                if (templateNpcGetterFormlink == null)
                {
                    untemplatedNpc = null;
                    break;
                }

                if (!templateNpcGetterFormlink.TryResolve(State!.LinkCache, out var templateNpcGetter))
                {
                    untemplatedNpc = null;
                    break;
                }

                untemplatedNpc = templateNpcGetter;
            }

            return untemplatedNpc;
        }

        private static Dictionary<ISpellGetter, SpellInfo> GetSpellInfoList()
        {
            bool useModInclude = Settings.Value.SpellModInclude.Count > 0 || Settings.Value.SpellModNameInclude.Count > 0;
            bool useSpellExclude = Settings.Value.SpellExclude.Count > 0;
            Dictionary<ISpellGetter, SpellInfo> spellInfoList = new();
            foreach (var spellGetterContext in EnumerateSpellGetterContexts())
            {
                // skip invalid
                if (spellGetterContext == null) continue;

                string npcDebugID = "";
                if (Settings.Value.Debug.IsDebugSpell)
                {
                    DebugSpell = false;
                    if (spellGetterContext.Record.EditorID.HasAnyFromList(Settings.Value.Debug.SpellEDIDListForDebug))
                    {
                        npcDebugID = $"{nameof(GetSpellInfoList)}/{ nameof(spellGetterContext.Record.EditorID)}";
                        Console.WriteLine($"{npcDebugID} debug begin!");
                        DebugSpell = true;
                    }
                }                

                var spellGetter = spellGetterContext.Record;

                if (DebugSpell) Console.WriteLine($"{nameof(GetSpellInfoList)}/{nameof(spellGetterContext.Record.EditorID)} 1");
                var sourceModKey = State!.LinkCache.ResolveAllContexts<ISpell, ISpellGetter>(spellGetter.FormKey).Last().ModKey;
                if (useModInclude && !Settings.Value.SpellModInclude.Contains(sourceModKey)
                    && !sourceModKey.FileName.String.HasAnyFromList(Settings.Value.SpellModNameInclude)) continue;

                if (DebugSpell) Console.WriteLine($"{nameof(GetSpellInfoList)}/{nameof(spellGetterContext.Record.EditorID)} 2");
                if (spellGetter.Type != SpellType.Spell) continue;
                if (DebugSpell) Console.WriteLine($"{nameof(GetSpellInfoList)}/{nameof(spellGetterContext.Record.EditorID)} 3");
                if (spellInfoList.ContainsKey(spellGetter)) continue;
                if (DebugSpell) Console.WriteLine($"{nameof(GetSpellInfoList)}/{nameof(spellGetterContext.Record.EditorID)} 4");
                if (string.IsNullOrWhiteSpace(spellGetter.EditorID)) continue;
                if (DebugSpell) Console.WriteLine($"{nameof(GetSpellInfoList)}/{nameof(spellGetterContext.Record.EditorID)} 5");
                if (useSpellExclude && spellGetter.EditorID.HasAnyFromList(Settings.Value.SpellExclude)) continue;

                if (DebugSpell) Console.WriteLine($"{nameof(GetSpellInfoList)}/{nameof(spellGetterContext.Record.EditorID)} 6");
                var spellInfo = GetSpellInfo(spellGetter);

                if (DebugSpell) Console.WriteLine($"{nameof(GetSpellInfoList)}/{nameof(spellGetterContext.Record.EditorID)} 7");
                if (spellInfo != null) spellInfoList.TryAdd(spellGetter, spellInfo);
            }

            return spellInfoList;
        }

        private static IEnumerable<Mutagen.Bethesda.Plugins.Cache.IModContext<ISkyrimMod, ISkyrimModGetter, ISpell, ISpellGetter>?> EnumerateSpellGetterContexts()
        {
            if (Settings.Value.IsSpellsFromSpelltomes)
            {
                foreach (var bookContext in State!.LoadOrder.PriorityOrder.Book().WinningContextOverrides())
                {
                    if (bookContext.Record.Teaches is not BookSpell bookSpell) continue;

                    if (!bookSpell.Spell.TryResolveContext<ISkyrimMod, ISkyrimModGetter, ISpell, ISpellGetter>(State!.LinkCache, out var spellContext)) continue;

                    yield return spellContext;
                }
            }
            else foreach (var spellContext in State!.LoadOrder.PriorityOrder.Spell().WinningContextOverrides()) yield return spellContext;
        }

        private static SpellInfo? GetSpellInfo(ISpellGetter spellGetter)
        {
            SpellInfo spellInfo = new();
            uint curCost = default;
            bool firstMainIsSet = false; // control to set first main effect because curcost is 0
            foreach (var mEffect in spellGetter.Effects)
            {
                if (mEffect == null
                    || mEffect.Data == null
                    || mEffect.BaseEffect.IsNull
                    || mEffect.BaseEffect.FormKey.IsNull) continue;

                if (!mEffect.BaseEffect.TryResolve(State!.LinkCache, out var effect)) continue;

                var effectMagicSkillActorValue = effect.MagicSkill;

                // add required skills and thir max required levels
                if (!IsMagicSkill(effectMagicSkillActorValue)) continue;

                var skill = GetSkillByActorValue(effectMagicSkillActorValue);

                AddUpdateSkill(spellInfo.RequiredSkills, skill, effect.MinimumSkillLevel);

                // set spell info
                float mag = mEffect.Data.Magnitude;
                if (mag < 1) mag = 1F;

                int dur = mEffect.Data.Duration;
                if (dur == 0) dur = 10;

                // calculate main skill and effect
                var cost = CalcCost(effect.BaseCost, mag, dur);
                if (!firstMainIsSet || cost > curCost)
                {
                    firstMainIsSet = true;
                    spellInfo.MainSkill = skill;
                    curCost = cost;
                    spellInfo.MainEffect = effect;
                }
            }

            return !firstMainIsSet ? null : spellInfo;
        }

        private static uint CalcCost(float effectBaseCost, float mag, int dur)
        {
            return (uint)Math.Floor(effectBaseCost * Math.Pow((mag * dur / 10), 1.1));
        }

        private static void AddUpdateSkill(Dictionary<Skill, uint> requiredSkills, Skill skill, uint minimumSkillLevel)
        {
            if (requiredSkills.ContainsKey(skill))
            {
                if (requiredSkills[skill] < minimumSkillLevel) requiredSkills[skill] = minimumSkillLevel;
            }
            else requiredSkills.Add(skill, minimumSkillLevel);
        }

        private static Skill GetSkillByActorValue(ActorValue effectMagicSkillActorValue)
        {
            return (Skill)Enum.Parse(typeof(Skill), effectMagicSkillActorValue.ToString());
        }

        private static bool CanGetTheSpell(NPCInfo npcInfo, KeyValuePair<ISpellGetter, SpellInfo> spellInfo)
        {
            if (DebugSpell) Console.WriteLine("CanGetTheSpell 1");
            //if (npcGetter.PlayerSkills == null) return false;
            if (spellInfo.Value.MainEffect == null) return false;
            if (DebugSpell) Console.WriteLine("CanGetTheSpell 2");
            if (spellInfo.Value.MainEffect.Keywords == null) return false;
            if (DebugSpell) Console.WriteLine("CanGetTheSpell 3");

            foreach (var requiredSkillInfo in spellInfo.Value.RequiredSkills)
            {
                if (DebugSpell) Console.WriteLine("CanGetTheSpell 4");
                if (requiredSkillInfo.Value > npcInfo.SkillLevels[requiredSkillInfo.Key]) return false;
                if (DebugSpell) Console.WriteLine("CanGetTheSpell 4.1");
                //if (npcGetter.PlayerSkills.SkillValues.First(s => s.Key == requiredSkillInfo.Key).Value < requiredSkillInfo.Value) return false;
            }

            if (DebugSpell) Console.WriteLine("CanGetTheSpell 5");
            var spellValidKeywords = new List<IKeywordGetter>();
            foreach (var keywordFormLinkGetter in spellInfo.Value.MainEffect!.Keywords)
            {
                if (keywordFormLinkGetter.IsNull) continue;

                if (!keywordFormLinkGetter.TryResolve(State!.LinkCache, out var keyword)) continue;

                var edid = keyword.EditorID;
                if (string.IsNullOrWhiteSpace(edid)) continue;
                if (keyword.EditorID.HasAnyFromList(Settings.Value.EffectKeywordInclude)) spellValidKeywords.Add(keyword);
            }


            if (DebugSpell) Console.WriteLine("CanGetTheSpell 6");
            if (spellValidKeywords.Count == 0) return false;

            if (DebugSpell) Console.WriteLine("CanGetTheSpell 7");
            if (!npcInfo.HandEffects.ContainsKey(spellInfo.Key.EquipmentType.FormKey)) return false;

            if (DebugSpell) Console.WriteLine("CanGetTheSpell 8");
            var npcSpellsEffectsValidKeywords = npcInfo.HandEffects[spellInfo.Key.EquipmentType.FormKey];
            if (npcSpellsEffectsValidKeywords == null) return false;

            if (DebugSpell) Console.WriteLine("CanGetTheSpell 9");
            foreach (var keywordGetter in spellValidKeywords) if (npcSpellsEffectsValidKeywords.Contains(keywordGetter)) return true;

            if (DebugSpell) Console.WriteLine("CanGetTheSpell 10");
            if (DebugSpell) Console.WriteLine($"{nameof(spellValidKeywords)}:\n{string.Join("\n", spellValidKeywords.Select(k=>k.EditorID))}\n\n{nameof(npcSpellsEffectsValidKeywords)}:\n{string.Join("\n", npcSpellsEffectsValidKeywords.Select(k=>k.EditorID))}");
            return false;
        }

        private static bool IsMagicSkill(ActorValue effectMagicSkill)
        {
            return effectMagicSkill == ActorValue.Alteration
                || effectMagicSkill == ActorValue.Conjuration
                || effectMagicSkill == ActorValue.Destruction
                || effectMagicSkill == ActorValue.Illusion
                || effectMagicSkill == ActorValue.Restoration;
        }
    }
}
